# Generated by Django 6.0.2 on 2026-02-11 08:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('total_records', models.IntegerField(default=0)),
                ('imported_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Import Log',
                'verbose_name_plural': 'Import Logs',
                'db_table': 'import_logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text="Influencer's full name", max_length=255)),
                ('contact', models.CharField(blank=True, help_text='10-digit Indian mobile number (without country code)', max_length=10, null=True, validators=[django.core.validators.RegexValidator(code='invalid_contact', message='Contact must be exactly 10 digits', regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email address (lowercase)', max_length=255, null=True)),
                ('ig_link', models.URLField(blank=True, help_text='Full Instagram profile URL', max_length=500, null=True)),
                ('instagram_handle', models.CharField(blank=True, db_index=True, help_text='Instagram username (without @)', max_length=100, null=True)),
                ('followers', models.IntegerField(blank=True, db_index=True, help_text='Instagram follower count', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(blank=True, db_index=True, help_text='Geographic location (city/state)', max_length=200, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Couple', 'Couple'), ('Kid', 'Kid'), ('Other', 'Other')], db_index=True, help_text='Gender category', max_length=20, null=True)),
                ('genre', models.TextField(blank=True, help_text='Content niches (pipe-separated: Fashion|Lifestyle|Beauty)', null=True)),
                ('brand', models.TextField(blank=True, help_text='Brand collaboration history', null=True)),
                ('address', models.TextField(blank=True, help_text='Physical address', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, help_text='Last Instagram follower sync timestamp', null=True)),
                ('search_vector', models.TextField(blank=True, editable=False, help_text='Full-text search index (auto-generated)', null=True)),
            ],
            options={
                'verbose_name': 'Influencer',
                'verbose_name_plural': 'Influencers',
                'db_table': 'influencers',
                'ordering': ['-followers', 'name'],
                'indexes': [models.Index(fields=['name'], name='idx_name'), models.Index(fields=['instagram_handle'], name='idx_ig_handle'), models.Index(fields=['email'], name='idx_email'), models.Index(fields=['followers'], name='idx_followers'), models.Index(fields=['location'], name='idx_location'), models.Index(fields=['gender'], name='idx_gender'), models.Index(fields=['-followers'], name='idx_followers_desc')],
            },
        ),
        migrations.CreateModel(
            name='BrandCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, help_text='Brand/company name', max_length=255)),
                ('campaign_name', models.CharField(blank=True, help_text='Specific campaign name', max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='completed', help_text='Campaign status', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Campaign start date', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Campaign end date', null=True)),
                ('compensation', models.DecimalField(blank=True, decimal_places=2, help_text='Compensation amount (INR)', max_digits=10, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the collaboration', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('influencer', models.ForeignKey(help_text='Associated influencer', on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to='influencers.influencer')),
            ],
            options={
                'verbose_name': 'Brand Collaboration',
                'verbose_name_plural': 'Brand Collaborations',
                'db_table': 'brand_collaborations',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['brand_name'], name='idx_brand_name'), models.Index(fields=['status'], name='idx_collab_status'), models.Index(fields=['-start_date'], name='idx_start_date_desc')],
            },
        ),
    ]
